description: Submit your appeal
name: sscs-tribunals-frontend
home: https://github.com/hmcts/sscs-submit-your-appeal
apiVersion: v2
appVersion: "1.0"
version: 0.2.72
maintainers:
  - name: HMCTS SSCS Team
dependencies:
  - name: nodejs
    version: 3.2.0
    repository: 'oci://hmctsprod.azurecr.io/helm'
  - name: hmcts-redis
    version: 0.8.0
    repository: "oci://hmctsprod.azurecr.io/helm"
    condition: hmcts-redis.enabled
  - name: idam-pr
    version: 2.3.1
    repository: 'oci://hmctsprod.azurecr.io/helm'
    condition: idam-pr.enabled
