nodejs:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    NODE_ENV: "aat"
    PCQ_URL: "https://pcq.aat.platform.hmcts.net"
    FT_WELSH: true
    PCQ_ENABLED: true
    IBC_NI_POSTCODES_FEATURE: true

