const types = {
  attendanceAllowance: 'Attendance Allowance',
  bereavementBenefit: 'Bereavement Benefit',
  carersAllowance: "Carer's Allowance",
  childBenefit: 'Child Benefit Lone Parent',
  disabilityLivingAllowance: 'Disability Living Allowance (DLA)',
  employmentAndSupportAllowance: 'Employment and Support Allowance (ESA)',
  homeResponsibilitiesProtection: 'Home Responsibilities Protection',
  housingBenefit: 'Housing Benefit (HB)',
  incapacityBenefit: 'Incapacity Benefit',
  incomeSupport: 'Income Support',
  industrialInjuriesDisablement: 'Industrial Injuries Disablement Benefit',
  jobseekersAllowance: 'Jobseeker’s Allowance (JSA)',
  maternityAllowance: 'Maternity Allowance',
  personalIndependencePayment: 'Personal Independence Payment (PIP)',
  severeDisablementAllowance: 'Severe Disablement Allowance',
  socialFund: 'Social Fund',
  universalCredit: 'Universal Credit (UC)',
  childCare: '30 Hours Free Childcare Scheme',
  bereavementSupportPaymentScheme: 'Bereavement Support Payment Scheme',
  taxCredits: 'Tax Credits',
  contractedOut: 'Contracted Out Employment Group',
  compensationRecovery: 'Compensation Recovery Unit',
  healthPregnancy: 'Health in Pregnancy Grant',
  industrialDeathBenefit: 'Industrial Death Benefit',
  pensionCredits: 'Pension Credits',
  retirementPension: 'Retirement Pension',
  taxFreeChildcare: 'Tax-Free Childcare Scheme',
  disabilityWorkAllowance: 'Disability Working Allowance'
};

module.exports = types;
