infrastructure_env = "preprod"
node_environment = "aat"
evidence_upload_enabled = "true"
https_only_flag = "false"
postcode_checker_enabled = "true"
postcode_checker_allowed_rpcs = "birmingham,liverpool,sutton,leeds,newcastle,cardiff"
sya_hostname  = "benefit-appeal.nonprod.platform.hmcts.net"
