infrastructure_env = "preprod"
node_environment = "aat"
sya_hostname  = "benefit-appeal.nonprod.platform.hmcts.net"
evidence_upload_enabled = "true"
https_only_flag = "false"
postcode_checker_enabled = "true"
