infrastructure_env = "preprod"
node_environment = "preview"
sya_hostname  = "sscs-tribunals-frontend-preview.service.core-compute-preview.internal"
evidence_upload_enabled = "true"
https_only_flag = "false"
