infrastructure_env = "dev"
sya_server_port = "3000"
node_environment = "sandbox"
tribunals_case_api = "http://sscs-tribunals-api-sandbox-staging.service.core-compute-sandbox.internal/"
sya_hostname  = "benefit-appeal.demo.platform.hmcts.net"
