/*
BMP
DOC
DOCX
DOT
DOTX
JPEG
JPG
PDF
PNG
POT
POTX
PPA
PPS
PPSX
PPT
PPTX
TIF
TIFF
TXT
XLA
XLS
XLSB
XLSX
XLT
XLTX
*/
module.exports = [
  '.jpg',
  '.jpeg',
  '.bmp',
  '.tif',
  '.tiff',
  '.png',
  '.pdf',
  '.txt',
  '.doc',
  '.dot',
  '.docx',
  '.dotx',
  '.xls',
  '.xlt',
  '.xla',
  '.xlsx',
  '.xltx',
  '.xlsb',
  '.ppt',
  '.pot',
  '.pps',
  '.ppa',
  '.pptx',
  '.potx',
  '.ppsx',
  'image/jpeg',
  'application/pdf',
  'image/tiff',
  'image/png',
  'image/bmp',
  'text/plain',
  'application/msword',
  'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  'application/vnd.openxmlformats-officedocument.wordprocessingml.template',
  'application/vnd.ms-excel',
  'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  'application/vnd.openxmlformats-officedocument.spreadsheetml.template',
  'application/vnd.ms-powerpoint',
  'application/vnd.openxmlformats-officedocument.presentationml.presentation',
  'application/vnd.openxmlformats-officedocument.presentationml.template',
  'application/vnd.openxmlformats-officedocument.presentationml.slideshow'
];