const languages = [
  'Acholi',
  'Afrikaans',
  'Akan',
  'Albanian',
  'Algerian',
  'Amharic',
  'Arabic',
  'Arabic (Middle Eastern)',
  'Arabic (North African)',
  'Armenian',
  'Ashanti',
  'Assyrian',
  'Ateso',
  'Azerbajani (aka Nth Azari)',
  'Bajan (West Indian)',
  'Bajuni',
  'Baluchi',
  'Bambara',
  'Banjuni',
  'Bassa',
  'Belorussian',
  'Benba (Bemba)',
  'Bengali',
  'Bengali (Sylheti)',
  'Benin/Edo',
  'Berber',
  'Bhutanese',
  'Bihari',
  'Bilin',
  'Bravanese',
  'Brong',
  'Bulgarian',
  'Burmese',
  'Cambellpuri',
  'Cantonese',
  'Cebuano',
  'Chechen',
  'Chichewa',
  'Chittagonain',
  'Creole (English)',
  'Creole (French)',
  'Creole (Portuguese)',
  'Creole (Spanish)',
  'Czech',
  'Danish',
  'Dari',
  'Dinka',
  'Dioula',
  'Douala',
  'Dutch',
  'Efik',
  'Esan',
  'Estonian',
  'Ewe',
  'Ewondo',
  'Fanti',
  'Farsi',
  'Feyli',
  'Fijian',
  'Flemish',
  'French',
  'French (Arabic)',
  'French (African)',
  'Fula',
  'Ga',
  'Gallacian',
  'Georgian',
  'German',
  'Gorani',
  'Greek',
  'Gujarati',
  'Gurage',
  'Guran',
  'Hakka',
  'Hausa',
  'Hebrew',
  'Herero',
  'Hindi',
  'Hindko',
  'Hokkien',
  'Hungarian',
  'Ibibio',
  'Igbo (Also Known As Ibo)',
  'Ilocano',
  'Indonesian',
  'Isoko',
  'Italian',
  'Jamaican',
  'Japanese',
  'Javanese',
  'Kachi',
  'Karon',
  'Kashmiri',
  'Khalanga',
  'Khmer',
  'Khymer Khymer',
  'Kibanjuni',
  'Kichagga',
  'Kikongo',
  'Kikuyu',
  'Kinyarwandan',
  'Kirundi',
  'Kiswahili',
  'Konkani',
  'Korean',
  'Krio (Sierra Leone)',
  'Kru',
  'Kurdish (Bardini)',
  'Kurdish (Kurmanji)',
  'Kurdish (Sorani)',
  'Kutchi',
  'Kyrgyz',
  'Lango',
  'Latvian',
  'Lingala',
  'Lithuanian',
  'Luba (Tshiluba)',
  'Lugandan',
  'Luo',
  'Luo (Kenyan)',
  'Luo (Ugandan[Acholi District])',
  'Luo (Ugandan[Lango District])',
  'Lusoga',
  'Macedonian',
  'Maghreb',
  'Malay',
  'Malayalam',
  'Maldivian',
  'Malinke',
  'Maltese',
  'Mandarin',
  'Mandinka',
  'Marathi',
  'Masaaba',
  'Mende',
  'Mina',
  'Mirpuri',
  'Moldovan',
  'Mongolian',
  'Monokutuba',
  'Navsari',
  'Ndebele',
  'Nepali',
  'Ngwa',
  'Northern Hindko',
  'Norwegian',
  'Nyankole',
  'Nzima',
  'Oromo',
  'Pahari',
  'Pampangan',
  'Pangasinan',
  'Pathwari',
  'Patois',
  'Pidgin English',
  'Polish',
  'Portuguese',
  'Pothohari',
  'Punjabi',
  'Punjabi (Indian)',
  'Punjabi (Pakistani)',
  'Pushtu (Also Known As Pashto)',
  'Putonghue',
  'Roma',
  'Romanian',
  'Romany',
  'Rukiga',
  'Runyoro',
  'Russian',
  'Rutoro',
  'Sakata',
  'Sarahuleh',
  'Saraiki (Seraiki)',
  'Sarpo',
  'Senegal (French)',
  'Serbo-Croatian',
  'Setswana',
  'Shina',
  'Shona',
  'Sindhi',
  'Sinhalese',
  'Slovak',
  'Slovenian',
  'Somali',
  'Spanish',
  'Susu',
  'Swahili',
  'Swedish',
  'Sylheti',
  'Tagalog',
  'Taiwanese',
  'Tamil',
  'Telugu',
  'Temne',
  'Thai',
  'Tibetan',
  'Tigre',
  'Tigrinya',
  'Toura',
  'Turkish',
  'Turkmen',
  'Twi',
  'Uighur',
  'Ukrainian',
  'Urdu',
  'Urohobo',
  'Uzbek',
  'Vietnamese',
  'Visayan',
  'Welsh',
  'Wolof',
  'Xhosa',
  'Yoruba',
  'Zaghawa',
  'Zaza',
  'Zulu'
];

module.exports = languages;
